verbose mode + fixes
pln-fing-udelar/news-processor pull request #4
Opened 2022-10-14 19:12 UTC by filevich

* modo verbose opcional (output a stderr; incluido tqdm)
* `utils.assure_path`
* handle fail
* tiny fixes

2022-10-15 00:37 UTC, gmarco10 requested changes

2022-10-15 00:37 UTC, gmarco10 commented on src/el_pais_parser.py
> +    parser = argparse.ArgumentParser()
estos parametros aplican para la diaria, teniendo en cuenta que ya estan definidos como default en el metodo de parseo de 'el pais', no creo que sea necesario esto

2022-10-15 00:37 UTC, gmarco10 approved these changes

2022-10-15 00:38 UTC, gmarco10 commented on src/el_pais_parser.py
> +    parser = argparse.ArgumentParser()
@filevich cuando puedas, hace este cambio y lo mergeamos, a mi me va a servir lo que agregaste para el parseo de el_pais que vengo haciendo

2022-10-18 18:04 UTC, filevich commented on src/el_pais_parser.py
> +    parser = argparse.ArgumentParser()
Ahí lo arreglé. A priori puede parecer redundante que los parametros se encuentren repetidos tanto en la función `parse_data` como en el `argparse`, el tema es que así pueden ser editados tanto a nivel de comando como a nivel de "librería" (o "prgramaticamente", digamos, no sé si me expliqué bien ?).

2022-10-18 18:05 UTC, merged